#!/bin/sh
# Run meeting-capture's unit tests.
#
# Compiles the daemon as a plain module — everything from "// MARK: - Main" down
# is entry point and gets stripped, leaving only declarations — and runs
# tests/Tests.swift against it. The accessibility API, processes, and real time
# are not exercised here; these cover the pure logic: clock parsing,
# timestamps, slugs, wrapping, and caption-segment identity.
set -euo pipefail

cd "$(dirname "$0")/.."
out=$(mktemp -d)
trap 'rm -rf "$out"' EXIT

{
  echo '// Generated by tests/run.sh from bin/meeting-capture (entry point stripped).'
  tail -n +2 bin/meeting-capture | sed '/^\/\/ MARK: - Main$/,$d'
} > "$out/library.swift"
cp tests/Tests.swift "$out/main.swift"
swiftc -o "$out/tests" "$out/library.swift" "$out/main.swift"

# The stripped build never sees post-MARK code, so type-check the full entry
# point separately — otherwise nothing would catch breakage below the marker.
cp bin/meeting-capture "$out/entry.swift"
swiftc -o "$out/entry-check" "$out/entry.swift"

"$out/tests"
